export const  GET_PAGE_ITEMS_REQUEST = "GET_PAGE_ITEMS_REQUEST"; 
export const  GET_PAGE_ITEMS_SUCSESS = "GET_PAGE_ITEMS_SUCSESS";
export const  GET_PAGE_ITEMS_RFAILURE = "GET_PAGE_ITEMS_RFAILURE";

export const  POST_ITEM_REQUEST = "POST_ITEM_REQUEST";
export const  POST_ITEM_SUCSESS = "POST_ITEM_SUCSESS";
export const  POST_ITEM_RFAILURE = "POST_ITEM_RFAILURE";

export const  PATCH_ITEM_REQUEST = "PATCH_ITEM_REQUEST";
export const  PATCH_ITEM_SUCSESS = "PATCH_ITEM_SUCSESS";
export const  PATCH_ITEM_RFAILURE = "PATCH_ITEM_RFAILURE";

export const  DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const  DELETE_ITEM_SUCSESS = "DELETE_ITEM_SUCSESS";
export const  DELETE_ITEM_RFAILURE = "DELETE_ITEM_RFAILURE";



export const CHANGE_TEXT_SEARCH_TO_NULL ="CHANGE_TEXT_SEARCH_TO_NULL";
export const CHANGE_ACTIVE_PAGE ="CHANGE_ACTIVE_PAGE";
export const GET_ACTIVE_PAGE_TO_DEFAULT ="GET_ACTIVE_PAGE_TO_DEFAULT";
export const UPDATE_TEXT_SEARCH ="UPDATE_TEXT_SEARCH";
export const GET_TOTAL_PAGE ="GET_TOTAL_PAGE";

export const  GET_TOTAL_PAGE_REQUEST = "GET_TOTAL_PAGE_REQUEST";
export const  GET_TOTAL_PAGE_SUCSESS = "GET_TOTAL_PAGE_SUCSESS";
export const  GET_TOTAL_PAGE_RFAILURE = "GET_TOTAL_PAGE_RFAILURE";